<?php

/*
function hide_reviewer_in_fields(&$hidee) {		// For hiding review_in fields
	hide($hidee['field_project_review_r1_in']);
	hide($hidee['field_project_review_r2_in']);
	hide($hidee['field_project_review_r3_in']);
}

/*
 * Implementing hook_form_alter
 
function bfi_form_tweaks_form_alter(&$form, &$form_state, $form_id) {

//  dpm($form);

  switch ($form_id) {
  	case 'project_node_form':
		$count_reviewer = count($form['field_project_reviewers']['und']) - 13;
  		for ($i = 0; $i < $count_reviewer; $i++) {
	  		hide_reviewer_in_fields($form['field_project_reviewers']['und'][$i]['relation_options']);
  		}
  		break;
  	case 'relation_ui_edit_form':
  		hide_reviewer_in_fields($form);
  		break;
  }

}
*/

function bfi_form_tweaks_form_alter(&$form, &$form_state, $form_id) {

//  dpm($form);

}

/*
function bfi_form_tweaks_field_widget_form_alter(&$element, &$form_state, $context) {
  dpm ("\n bfi_field_widget_form_alter");
  dpm ("\n element: ");
  dpm ($element);
  dpm ("\n widget type: ");
  dpm ($context['instance']['widget']['type']);
}
*/

$mod_name = 'bfi_form_tweaks';
$path = drupal_get_path('module', $mod_name).'/css/'.$mod_name.'.css';
// Currently set to inline b/c the css file reference wouldn't work for some reason. Not ideal. Debug this when have time.
$inline = '
form div.field-name-field-project-review-r1-in,
form div.field-name-field-project-review-r2-in,
form div.field-name-field-project-review-r3-in,
form div.field-name-field-project-review-jury-in,
form div.field-name-field-project-review-score-rds {
  display: none !important;
}


div.view-bfc-project-review-form-block div.entityform-type-entityform-type,
div.view-bfc-project-review-form-block form.entitytype-bfc_project_review-form div.submissions-link {
  display: none !important;
}

div#payment-method-wrapper table tr.payment-line_item-total,
div#payment-method-wrapper div.field-name-field-payment-type,
div#payment-method-wrapper div.field-name-field-payment-app-id {
  display: none;
}

body.fubik div.form-item div.description {
  bottom: 110%;
}';
drupal_add_css($inline, array('type'=>'inline', 'group' => CSS_DEFAULT, 'every_page' => TRUE));
drupal_add_css('//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css', array('group' => CSS_THEME, 'type' => 'external'));
